name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build and run tests
        run: mvn -B clean test

      - name: Generate JaCoCo report
        run: mvn jacoco:report

      - name: Run PIT mutation testing
        run: mvn -DskipTests=false org.pitest:pitest-maven:mutationCoverage

      - name: Upload test results and coverage
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-and-coverage
          path: target/site/jacoco
